/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  public static void main(String[] args) {
    int[] nums = { 1, 2, 3 };
    // System.out.println(new App().getGreeting());
    System.out.println(new LongestConsecutive().longestConsecutive(nums));
  }

}
