/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  // @Test void appHasAGreeting() {
  // App classUnderTest = new App();
  // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  // }
  @Test
  void fourConsecutiveElements() {
    LongestConsecutive classUnderTest = new LongestConsecutive();
    assertEquals(4, classUnderTest.longestConsecutive(new int[] { 100, 4, 200, 1, 3, 2 }),
        "Should be 4 consecutive numbers");
  }
}
